# This is a basic workflow to help you get started with Actions

name: Build Vue App

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Building docker
        run: docker build . --file infra/docker/vue/Dockerfile --tag app:$(date +%s)

      - name: Install npm
        run: docker container exec -it app bash -c "cd frontend && npm install"
        
      - name: Building app
        run: docker container exec -it app bash -c "cd frontend && npm run build"
