name: Build Vue App

on:
  pull_request:
    branches:
      - master
      - staging
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.base_ref }}

    steps:
      - uses: actions/checkout@v3

      - name: Building docker
        run: docker-compose up -d --build

      - name: Install npm
        run: |
          mkdir app/node_modules
          chmod 777 -R app/node_modules
          chmod 777 app/package-lock.json
          docker container exec -i app bash -c "npm install"
          sudo chown -R runner app

      - name: Set env
        working-directory: ./app
        run: |
          touch .env
          sudo chmod 664 .env
          echo "ENV=${{ secrets.ENV }}" >> .env

      - name: Building app
        run: |
          mkdir app/dist
          chmod 777 -R app/dist
          docker container exec -i app bash -c "npm run build"
